{-# LANGUAGE DeriveDataTypeable #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-missing-fields #-}
{-# OPTIONS_GHC -fno-warn-missing-signatures #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-----------------------------------------------------------------
-- Autogenerated by Thrift Compiler (0.12.0)                      --
--                                                             --
-- DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING --
-----------------------------------------------------------------

module Shared_Types where
import Prelude (($), (.), (>>=), (==), (++))
import qualified Prelude as P
import qualified Control.Exception as X
import qualified Control.Monad as M ( liftM, ap, when )
import Data.Functor ( (<$>) )
import qualified Data.ByteString.Lazy as LBS
import qualified Data.Hashable as H
import qualified Data.Int as I
import qualified Data.Maybe as M (catMaybes)
import qualified Data.Text.Lazy.Encoding as E ( decodeUtf8, encodeUtf8 )
import qualified Data.Text.Lazy as LT
import qualified GHC.Generics as G (Generic)
import qualified Data.Typeable as TY ( Typeable )
import qualified Data.HashMap.Strict as Map
import qualified Data.HashSet as Set
import qualified Data.Vector as Vector
import qualified Test.QuickCheck.Arbitrary as QC ( Arbitrary(..) )
import qualified Test.QuickCheck as QC ( elements )

import qualified Thrift as T
import qualified Thrift.Types as T
import qualified Thrift.Arbitraries as T


data SharedStruct = SharedStruct  { sharedStruct_key :: I.Int32
  , sharedStruct_value :: LT.Text
  } deriving (P.Show,P.Eq,G.Generic,TY.Typeable)
instance H.Hashable SharedStruct where
  hashWithSalt salt record = salt   `H.hashWithSalt` sharedStruct_key record   `H.hashWithSalt` sharedStruct_value record  
instance QC.Arbitrary SharedStruct where 
  arbitrary = M.liftM SharedStruct (QC.arbitrary)
          `M.ap`(QC.arbitrary)
  shrink obj | obj == default_SharedStruct = []
             | P.otherwise = M.catMaybes
    [ if obj == default_SharedStruct{sharedStruct_key = sharedStruct_key obj} then P.Nothing else P.Just $ default_SharedStruct{sharedStruct_key = sharedStruct_key obj}
    , if obj == default_SharedStruct{sharedStruct_value = sharedStruct_value obj} then P.Nothing else P.Just $ default_SharedStruct{sharedStruct_value = sharedStruct_value obj}
    ]
from_SharedStruct :: SharedStruct -> T.ThriftVal
from_SharedStruct record = T.TStruct $ Map.fromList $ M.catMaybes
  [ (\_v2 -> P.Just (1, ("key",T.TI32 _v2))) $ sharedStruct_key record
  , (\_v2 -> P.Just (2, ("value",T.TString $ E.encodeUtf8 _v2))) $ sharedStruct_value record
  ]
write_SharedStruct :: T.Protocol p => p -> SharedStruct -> P.IO ()
write_SharedStruct oprot record = T.writeVal oprot $ from_SharedStruct record
encode_SharedStruct :: T.StatelessProtocol p => p -> SharedStruct -> LBS.ByteString
encode_SharedStruct oprot record = T.serializeVal oprot $ from_SharedStruct record
to_SharedStruct :: T.ThriftVal -> SharedStruct
to_SharedStruct (T.TStruct fields) = SharedStruct{
  sharedStruct_key = P.maybe (sharedStruct_key default_SharedStruct) (\(_,_val4) -> (case _val4 of {T.TI32 _val5 -> _val5; _ -> P.error "wrong type"})) (Map.lookup (1) fields),
  sharedStruct_value = P.maybe (sharedStruct_value default_SharedStruct) (\(_,_val4) -> (case _val4 of {T.TString _val6 -> E.decodeUtf8 _val6; _ -> P.error "wrong type"})) (Map.lookup (2) fields)
  }
to_SharedStruct _ = P.error "not a struct"
read_SharedStruct :: T.Protocol p => p -> P.IO SharedStruct
read_SharedStruct iprot = to_SharedStruct <$> T.readVal iprot (T.T_STRUCT typemap_SharedStruct)
decode_SharedStruct :: T.StatelessProtocol p => p -> LBS.ByteString -> SharedStruct
decode_SharedStruct iprot bs = to_SharedStruct $ T.deserializeVal iprot (T.T_STRUCT typemap_SharedStruct) bs
typemap_SharedStruct :: T.TypeMap
typemap_SharedStruct = Map.fromList [(1,("key",T.T_I32)),(2,("value",T.T_STRING))]
default_SharedStruct :: SharedStruct
default_SharedStruct = SharedStruct{
  sharedStruct_key = 0,
  sharedStruct_value = ""}
