{-# LANGUAGE DeriveDataTypeable #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-missing-fields #-}
{-# OPTIONS_GHC -fno-warn-missing-signatures #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-----------------------------------------------------------------
-- Autogenerated by Thrift Compiler (0.12.0)                      --
--                                                             --
-- DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING --
-----------------------------------------------------------------

module AriviNetworkService where
import Prelude (($), (.), (>>=), (==), (++))
import qualified Prelude as P
import qualified Control.Exception as X
import qualified Control.Monad as M ( liftM, ap, when )
import Data.Functor ( (<$>) )
import qualified Data.ByteString.Lazy as LBS
import qualified Data.Hashable as H
import qualified Data.Int as I
import qualified Data.Maybe as M (catMaybes)
import qualified Data.Text.Lazy.Encoding as E ( decodeUtf8, encodeUtf8 )
import qualified Data.Text.Lazy as LT
import qualified GHC.Generics as G (Generic)
import qualified Data.Typeable as TY ( Typeable )
import qualified Data.HashMap.Strict as Map
import qualified Data.HashSet as Set
import qualified Data.Vector as Vector
import qualified Test.QuickCheck.Arbitrary as QC ( Arbitrary(..) )
import qualified Test.QuickCheck as QC ( elements )

import qualified Thrift as T
import qualified Thrift.Types as T
import qualified Thrift.Arbitraries as T


import Service_Types
import qualified AriviNetworkService_Iface as Iface
-- HELPER FUNCTIONS AND STRUCTURES --

data Ping_args = Ping_args deriving (P.Show,P.Eq,G.Generic,TY.Typeable)
instance H.Hashable Ping_args where
  hashWithSalt salt record = salt  
instance QC.Arbitrary Ping_args where 
  arbitrary = QC.elements [Ping_args]
from_Ping_args :: Ping_args -> T.ThriftVal
from_Ping_args record = T.TStruct $ Map.fromList $ M.catMaybes
  []
write_Ping_args :: T.Protocol p => p -> Ping_args -> P.IO ()
write_Ping_args oprot record = T.writeVal oprot $ from_Ping_args record
encode_Ping_args :: T.StatelessProtocol p => p -> Ping_args -> LBS.ByteString
encode_Ping_args oprot record = T.serializeVal oprot $ from_Ping_args record
to_Ping_args :: T.ThriftVal -> Ping_args
to_Ping_args (T.TStruct fields) = Ping_args{

  }
to_Ping_args _ = P.error "not a struct"
read_Ping_args :: T.Protocol p => p -> P.IO Ping_args
read_Ping_args iprot = to_Ping_args <$> T.readVal iprot (T.T_STRUCT typemap_Ping_args)
decode_Ping_args :: T.StatelessProtocol p => p -> LBS.ByteString -> Ping_args
decode_Ping_args iprot bs = to_Ping_args $ T.deserializeVal iprot (T.T_STRUCT typemap_Ping_args) bs
typemap_Ping_args :: T.TypeMap
typemap_Ping_args = Map.fromList []
default_Ping_args :: Ping_args
default_Ping_args = Ping_args{
}
data Ping_result = Ping_result  { ping_result_success :: P.Bool
  } deriving (P.Show,P.Eq,G.Generic,TY.Typeable)
instance H.Hashable Ping_result where
  hashWithSalt salt record = salt   `H.hashWithSalt` ping_result_success record  
instance QC.Arbitrary Ping_result where 
  arbitrary = M.liftM Ping_result (QC.arbitrary)
  shrink obj | obj == default_Ping_result = []
             | P.otherwise = M.catMaybes
    [ if obj == default_Ping_result{ping_result_success = ping_result_success obj} then P.Nothing else P.Just $ default_Ping_result{ping_result_success = ping_result_success obj}
    ]
from_Ping_result :: Ping_result -> T.ThriftVal
from_Ping_result record = T.TStruct $ Map.fromList $ M.catMaybes
  [ (\_v14 -> P.Just (0, ("success",T.TBool _v14))) $ ping_result_success record
  ]
write_Ping_result :: T.Protocol p => p -> Ping_result -> P.IO ()
write_Ping_result oprot record = T.writeVal oprot $ from_Ping_result record
encode_Ping_result :: T.StatelessProtocol p => p -> Ping_result -> LBS.ByteString
encode_Ping_result oprot record = T.serializeVal oprot $ from_Ping_result record
to_Ping_result :: T.ThriftVal -> Ping_result
to_Ping_result (T.TStruct fields) = Ping_result{
  ping_result_success = P.maybe (ping_result_success default_Ping_result) (\(_,_val16) -> (case _val16 of {T.TBool _val17 -> _val17; _ -> P.error "wrong type"})) (Map.lookup (0) fields)
  }
to_Ping_result _ = P.error "not a struct"
read_Ping_result :: T.Protocol p => p -> P.IO Ping_result
read_Ping_result iprot = to_Ping_result <$> T.readVal iprot (T.T_STRUCT typemap_Ping_result)
decode_Ping_result :: T.StatelessProtocol p => p -> LBS.ByteString -> Ping_result
decode_Ping_result iprot bs = to_Ping_result $ T.deserializeVal iprot (T.T_STRUCT typemap_Ping_result) bs
typemap_Ping_result :: T.TypeMap
typemap_Ping_result = Map.fromList [(0,("success",T.T_BOOL))]
default_Ping_result :: Ping_result
default_Ping_result = Ping_result{
  ping_result_success = P.False}
data SendRequest_args = SendRequest_args  { sendRequest_args_logid :: I.Int32
  , sendRequest_args_jsonReq :: LT.Text
  } deriving (P.Show,P.Eq,G.Generic,TY.Typeable)
instance H.Hashable SendRequest_args where
  hashWithSalt salt record = salt   `H.hashWithSalt` sendRequest_args_logid record   `H.hashWithSalt` sendRequest_args_jsonReq record  
instance QC.Arbitrary SendRequest_args where 
  arbitrary = M.liftM SendRequest_args (QC.arbitrary)
          `M.ap`(QC.arbitrary)
  shrink obj | obj == default_SendRequest_args = []
             | P.otherwise = M.catMaybes
    [ if obj == default_SendRequest_args{sendRequest_args_logid = sendRequest_args_logid obj} then P.Nothing else P.Just $ default_SendRequest_args{sendRequest_args_logid = sendRequest_args_logid obj}
    , if obj == default_SendRequest_args{sendRequest_args_jsonReq = sendRequest_args_jsonReq obj} then P.Nothing else P.Just $ default_SendRequest_args{sendRequest_args_jsonReq = sendRequest_args_jsonReq obj}
    ]
from_SendRequest_args :: SendRequest_args -> T.ThriftVal
from_SendRequest_args record = T.TStruct $ Map.fromList $ M.catMaybes
  [ (\_v20 -> P.Just (1, ("logid",T.TI32 _v20))) $ sendRequest_args_logid record
  , (\_v20 -> P.Just (2, ("jsonReq",T.TString $ E.encodeUtf8 _v20))) $ sendRequest_args_jsonReq record
  ]
write_SendRequest_args :: T.Protocol p => p -> SendRequest_args -> P.IO ()
write_SendRequest_args oprot record = T.writeVal oprot $ from_SendRequest_args record
encode_SendRequest_args :: T.StatelessProtocol p => p -> SendRequest_args -> LBS.ByteString
encode_SendRequest_args oprot record = T.serializeVal oprot $ from_SendRequest_args record
to_SendRequest_args :: T.ThriftVal -> SendRequest_args
to_SendRequest_args (T.TStruct fields) = SendRequest_args{
  sendRequest_args_logid = P.maybe (sendRequest_args_logid default_SendRequest_args) (\(_,_val22) -> (case _val22 of {T.TI32 _val23 -> _val23; _ -> P.error "wrong type"})) (Map.lookup (1) fields),
  sendRequest_args_jsonReq = P.maybe (sendRequest_args_jsonReq default_SendRequest_args) (\(_,_val22) -> (case _val22 of {T.TString _val24 -> E.decodeUtf8 _val24; _ -> P.error "wrong type"})) (Map.lookup (2) fields)
  }
to_SendRequest_args _ = P.error "not a struct"
read_SendRequest_args :: T.Protocol p => p -> P.IO SendRequest_args
read_SendRequest_args iprot = to_SendRequest_args <$> T.readVal iprot (T.T_STRUCT typemap_SendRequest_args)
decode_SendRequest_args :: T.StatelessProtocol p => p -> LBS.ByteString -> SendRequest_args
decode_SendRequest_args iprot bs = to_SendRequest_args $ T.deserializeVal iprot (T.T_STRUCT typemap_SendRequest_args) bs
typemap_SendRequest_args :: T.TypeMap
typemap_SendRequest_args = Map.fromList [(1,("logid",T.T_I32)),(2,("jsonReq",T.T_STRING))]
default_SendRequest_args :: SendRequest_args
default_SendRequest_args = SendRequest_args{
  sendRequest_args_logid = 0,
  sendRequest_args_jsonReq = ""}
data SendRequest_result = SendRequest_result  { sendRequest_result_success :: LT.Text
  , sendRequest_result_fail :: P.Maybe Failure
  } deriving (P.Show,P.Eq,G.Generic,TY.Typeable)
instance H.Hashable SendRequest_result where
  hashWithSalt salt record = salt   `H.hashWithSalt` sendRequest_result_success record   `H.hashWithSalt` sendRequest_result_fail record  
instance QC.Arbitrary SendRequest_result where 
  arbitrary = M.liftM SendRequest_result (QC.arbitrary)
          `M.ap`(M.liftM P.Just QC.arbitrary)
  shrink obj | obj == default_SendRequest_result = []
             | P.otherwise = M.catMaybes
    [ if obj == default_SendRequest_result{sendRequest_result_success = sendRequest_result_success obj} then P.Nothing else P.Just $ default_SendRequest_result{sendRequest_result_success = sendRequest_result_success obj}
    , if obj == default_SendRequest_result{sendRequest_result_fail = sendRequest_result_fail obj} then P.Nothing else P.Just $ default_SendRequest_result{sendRequest_result_fail = sendRequest_result_fail obj}
    ]
from_SendRequest_result :: SendRequest_result -> T.ThriftVal
from_SendRequest_result record = T.TStruct $ Map.fromList 
  (let exns = M.catMaybes [ (\_v27 -> (1, ("fail",from_Failure _v27))) <$> sendRequest_result_fail record]
  in if P.not (P.null exns) then exns else M.catMaybes
    [ (\_v27 -> P.Just (0, ("success",T.TString $ E.encodeUtf8 _v27))) $ sendRequest_result_success record
    , (\_v27 -> (1, ("fail",from_Failure _v27))) <$> sendRequest_result_fail record
    ]
    )
write_SendRequest_result :: T.Protocol p => p -> SendRequest_result -> P.IO ()
write_SendRequest_result oprot record = T.writeVal oprot $ from_SendRequest_result record
encode_SendRequest_result :: T.StatelessProtocol p => p -> SendRequest_result -> LBS.ByteString
encode_SendRequest_result oprot record = T.serializeVal oprot $ from_SendRequest_result record
to_SendRequest_result :: T.ThriftVal -> SendRequest_result
to_SendRequest_result (T.TStruct fields) = SendRequest_result{
  sendRequest_result_success = P.maybe (sendRequest_result_success default_SendRequest_result) (\(_,_val29) -> (case _val29 of {T.TString _val30 -> E.decodeUtf8 _val30; _ -> P.error "wrong type"})) (Map.lookup (0) fields),
  sendRequest_result_fail = P.maybe (P.Nothing) (\(_,_val29) -> P.Just (case _val29 of {T.TStruct _val31 -> (to_Failure (T.TStruct _val31)); _ -> P.error "wrong type"})) (Map.lookup (1) fields)
  }
to_SendRequest_result _ = P.error "not a struct"
read_SendRequest_result :: T.Protocol p => p -> P.IO SendRequest_result
read_SendRequest_result iprot = to_SendRequest_result <$> T.readVal iprot (T.T_STRUCT typemap_SendRequest_result)
decode_SendRequest_result :: T.StatelessProtocol p => p -> LBS.ByteString -> SendRequest_result
decode_SendRequest_result iprot bs = to_SendRequest_result $ T.deserializeVal iprot (T.T_STRUCT typemap_SendRequest_result) bs
typemap_SendRequest_result :: T.TypeMap
typemap_SendRequest_result = Map.fromList [(0,("success",T.T_STRING)),(1,("fail",(T.T_STRUCT typemap_Failure)))]
default_SendRequest_result :: SendRequest_result
default_SendRequest_result = SendRequest_result{
  sendRequest_result_success = "",
  sendRequest_result_fail = P.Nothing}
process_ping (seqid, iprot, oprot, handler) = do
  args <- read_Ping_args iprot
  (X.catch
    (do
      val <- Iface.ping handler
      let res = default_Ping_result{ping_result_success = val}
      T.writeMessage oprot ("ping", T.M_REPLY, seqid) $
        write_Ping_result oprot res)
    ((\_ -> do
      T.writeMessage oprot ("ping", T.M_EXCEPTION, seqid) $
        T.writeAppExn oprot (T.AppExn T.AE_UNKNOWN "")) :: X.SomeException -> P.IO ()))
process_sendRequest (seqid, iprot, oprot, handler) = do
  args <- read_SendRequest_args iprot
  (X.catch
    (X.catch
      (do
        val <- Iface.sendRequest handler (sendRequest_args_logid args) (sendRequest_args_jsonReq args)
        let res = default_SendRequest_result{sendRequest_result_success = val}
        T.writeMessage oprot ("sendRequest", T.M_REPLY, seqid) $
          write_SendRequest_result oprot res)
      (\e  -> do
        let res = default_SendRequest_result{sendRequest_result_fail = P.Just e}
        T.writeMessage oprot ("sendRequest", T.M_REPLY, seqid) $
          write_SendRequest_result oprot res))
    ((\_ -> do
      T.writeMessage oprot ("sendRequest", T.M_EXCEPTION, seqid) $
        T.writeAppExn oprot (T.AppExn T.AE_UNKNOWN "")) :: X.SomeException -> P.IO ()))
proc_ handler (iprot,oprot) (name,typ,seqid) = case name of
  "ping" -> process_ping (seqid,iprot,oprot,handler)
  "sendRequest" -> process_sendRequest (seqid,iprot,oprot,handler)
  _ -> do
    _ <- T.readVal iprot (T.T_STRUCT Map.empty)
    T.writeMessage oprot (name,T.M_EXCEPTION,seqid) $
      T.writeAppExn oprot (T.AppExn T.AE_UNKNOWN_METHOD ("Unknown function " ++ LT.unpack name))
process handler (iprot, oprot) = do
  T.readMessage iprot (
    proc_ handler (iprot,oprot))
  P.return P.True
